name: Test TIER2 release braches

on:
  pull_request:
    branches: ["release-0.7", "release-0.8"]
    paths-ignore:
      - "**.md"
  push:
    branches: ["release-0.7", "release-0.8"]
    paths-ignore:
      - "**.md"

jobs:
  test-tier2-release07:
    uses: konveyor/ci/.github/workflows/global-ci.yml@main
    if: ${{ github.ref == 'refs/heads/release-0.7' || github.event.pull_request.base.ref == 'release-0.7' }}
    with:
      tag: release-0.7
      operator_tag: v0.6.2  # TODO: update when operator tag for 0.7 is created
      api_tests_ref: ${{ github.ref }}
      api_tests_tiers: DEBUG=1 make test-tier2
      run_api_tests: true
      run_ui_tests: false
      api_hub_tests_ref: "release-0.7"
  test-tier2-release08:
    uses: konveyor/ci/.github/workflows/global-ci.yml@main
    if: ${{ github.ref == 'refs/heads/release-0.8' || github.event.pull_request.base.ref == 'release-0.8' }}
    with:
      tag: release-0.8
      operator_tag: v0.8.1-beta.2
      api_tests_ref: ${{ github.ref }}
      api_tests_tiers: DEBUG=1 make test-tier2
      run_api_tests: true
      run_ui_tests: false
      api_hub_tests_ref: "release-0.8"
